### ISSUE TITLE
pipeline linked data value invalid unless accessed in the module that produced it

### ISSUE THREAD

**Issue by theorm** [DHARPA-Project/kiara#11]
This happens in Kiara version `0.0.13`.

After Kiara has been upgraded in Lumy the workflows stopped producing data. After a debugging session I noticed that linked values (connected inputs) are marked as `valid=False` and an attempt to get data from them returns `None`. However, if these linked values are first retrieved as original values (using module ID and output ID where they were set) and then retrieved as linked values (connected module ID and input ID), the value is valid and value data is not `None` anymore.

Just to avoid spending time writing demonstration code, here is an example from the network analysis workflow:

Module A (`data_mapping`) produces an edges table which is available as output `edges`.
Module B (`create_graph`) takes an edges table and produces a graph which is available as output `graph`.

Module A `edges` output (`data_mapping.edges`) is connected to Module B `edges` input (`create_graph.edges`).

----
The following sequence of events produces an invalid `edges` input of Module B:

 * Middleware sets inputs of `data_mapping` step
 * This triggers execution of `process` function of Module A (`data_mapping`)
 * Process function sets output `edges`: `outputs.set_values(edges=edges)`
 * Middleware attempts to get `edges` table from the linked module Module B: `pipeline.get_step_input('create_graph', 'edges')`
 * The returned value has property `valid` set to `False`. Calling `value.get_value_data()` returns `None`.

----

The following modified sequence of events produces a valid `edges` input of Module B (changes in bold):

 * Middleware sets inputs of `data_mapping` step
 * This triggers execution of `process` function of Module A (`data_mapping`)
 * Process function sets output `edges`: `outputs.set_values(edges=edges)`
 * ***Process function immediately retrieves the value of `edges`: `outputs.get_value_obj('edges')`***
 * Middleware attempts to get `edges` table from the linked module Module B: `pipeline.get_step_input('create_graph', 'edges')`
 * ***The returned value has property `valid` set to `True`. Calling `value.get_value_data()` returns value data.***
 

----

This issue is a showstopper and blocks us from upgrading Kiara in Lumy from version `0.0.3` to `0.0.13` and using all new network analysis modules introduced  since version `0.0.3`.

**Comment by makkus** [comment]
Ok, most of the data registry code was completely rewritten in 0.1.0 (for example, linked values are totally gone), so I think it'd be worth trying again and see whether the issue is still there. If it is, or if you want me to fix it in a lower version, I'd really need some example code that can show me the exact issue, and help me reproduce it. I tried for a bit to come up with such code, following your description, but got lost fairly early in...

**Comment by theorm** [comment]
Fixed in kiara `0.1.0`.
