### ISSUE TITLE
Kiara raises an empty exception when a third party package exposes misconfigured Kiara modules or pipelines

### ISSUE THREAD

**Issue by theorm** [DHARPA-Project/kiara#15]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Kiara raises an exception without an explanatory message when it fails to load a module or a pipeline from a misconfigured third party package. 

The [module loading code](https://github.com/DHARPA-Project/kiara/blob/main/src/kiara/utils/class_loading.py#L477) raises a `NotImplementedError` if a third party package exposes a misconfigured Kiara pipeline or module. As it stands now Kiara raises an empty `NotImplementedError` and exits.

**Describe the solution you'd like**

Replace `NotImplementedError` with a warning that a certain pipeline or module plugin could not be loaded because the plugin type exposed is not supported and provide details which package exposed the misconfigured plug-in. Skip registering the misconfigured module and continue working with the registered modules.

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by makkus** [comment]
Actually, needs more work still.

**Comment by makkus** [comment]
If you want to ignore errors for misconfigured plugin entry points, you can do that now by creating the Kiara context object like:

```
from kiara.config import KiaraConfig
from kiara.kiara import Kiara 
kc = KiaraConfig(ignore_errors=True)
kiara = Kiara(config=kc)
```
