### ISSUE TITLE
Pipeline lazy initialisation

### ISSUE THREAD

**Issue by theorm** [DHARPA-Project/kiara#2]
Lazy initialisation of the pipeline [in the pipeline getter in workflow](https://github.com/DHARPA-Project/kiara/blob/develop/src/kiara/workflow.py#L63-L65) may cause issues when trying to get current pipeline state from the controller.

## This example raises and exception:

```python
from kiara import Kiara, PipelineController

kiara = Kiara.instance()

class MyController(PipelineController):
    pass

controller = MyController()
workflow = kiara.create_workflow('nand', controller=controller)

print(controller.get_current_pipeline_state().structure)
```
Output:
```
Exception: Pipeline not set yet.
```

## This example works

Accessing the getter to let the workflow create pipeline:

```python
from kiara import Kiara, PipelineController

kiara = Kiara.instance()

class MyController(PipelineController):
    pass

controller = MyController()
workflow = kiara.create_workflow('nand', controller=controller)

# TODO: access the pipeline here because it is lazily created
# in the getter.
workflow.pipeline

print(controller.get_current_pipeline_state().structure)
```

Output:

```
pipeline_id='nand_2' steps=....
```

**Comment by makkus** [comment]
Ignoring this for now, since it works in most cases. Connecting pipelines and controllers will a more managed approach in the future, so this will be re-written anyway.
