### ISSUE TITLE
Codeview / notebook rendering template

### ISSUE THREAD

**Issue by makkus** [DHARPA-Project/kiara#5]
This issue could be actually two issues, but not sure. Basically, we need a way to render the current state of a workflow in lumy. The suggestion was to render this a a Jupyter notebook that could also be downloaded and be run independently of lumy.

I've created a first version of the template here: 

https://github.com/DHARPA-Project/kiara/blob/metadata/src/kiara/resources/templates/notebook.ipynb.j2  

example output: 

https://deepnote.com/viewer/github/DHARPA-Project/kiara_modules.playground/blob/develop/dev/topic_modeling_v2.ipynb

This needs refinement and some restructuring.

**Comment by makkus** [comment]
The initial plan is for @MariellaCC  and me to do some initial cleanup and restructuring, and then for Mariella to present it to the other team-members.

**Comment by MariellaCC** [comment]
to-do-item for @MariellaCC: come up with paper sketches following meetings with @makkus that we will further discuss before submitting to the team (team feedback will probably be last week of July to have everyone)

**Comment by makkus** [comment]
The latest version of kiara has an initial notebook rendering feature, use like:

```
kiara render pipeline logic.xor a=true b=true > xor.ipynb
```
This can be used with any pipeline file / pipeline operation. Still early days, so some edge cases are not covered yet.

**Comment by MariellaCC** [comment]
should I attach the template prop we had come up together last year here?

**Comment by makkus** [comment]
Since this issue is still open, might as well put this here:

I've updated the template code slightly to reflect the code practices we've talked about (as far as I could remember). Also, I've changed the `render` subcommand slightly to be more informative. 

You can now get a list of all supported render combinations via:

```
pixi run kiara render list-renderers
```

Most of them are not interesting for anyone else but myself for now. The one that is important here can be called via:

```
kiara render --source-type pipeline --target-type jupyter_notebook item <name_of_or_path_to_pipeline> > notebook.ipynb
```
For the example `logic.xor` pipeline (including some inputs), this would look like:
```
kiara render --source-type pipeline --target-type jupyter_notebook item logic.xor inputs='{"a": true, "b": true}' > notebook.ipynb
jupyter lab notebook.ipynb
```

**Comment by makkus** [comment]
Closing this for now, since it has been implemented for some time with no feedback indicating it doesn't work or serve the intended purpose. Can always re-open...

**Comment by MariellaCC** [comment]
Did you bring up the feedback request in a dev meeting? Copying in @CBurge95 and @caro401 here just to be sure that this request for feedback was not missed.
