### ISSUE TITLE
error involving dag_cbor package

### ISSUE THREAD

**Issue by MariellaCC** [DHARPA-Project/kiara#53]
When running `from kiara.api import KiaraAPI` in a python 3.11 environment, I am getting the following error:

`ImportError: cannot import name 'Kind' from 'dag_cbor' (/opt/miniconda3/envs/dh_tagung/lib/python3.11/site-packages/dag_cbor/__init__.py)`.

If I run the same line in a python 3.10 environment I am not getting the error anymore, but it is still present when running it in google colab (which uses Python 3.8.10).

**Comment by makkus** [comment]
Thanks, I just had a quick look and it seems the `dag_cbor` package broke their API between version `0.3.0` and `0.3.1`. This is unfortunate, I'll have to release a new version of kiara to fix this. For now, pin the dependency to `0.3.0` in your virtual environment: `pip install dag_cbor==0.3.0`.

**Comment by MariellaCC** [comment]
ok thanks, indeed: `pip install -U dag_cbor==0.3.0` fixes the problem both in colab (python 3.8.10) and in Python 3.11 locally

**Comment by makkus** [comment]
Should be fixed as of 0.4.34.
