### ISSUE TITLE
Kiara 0.4.36 - Windows 10 - Enterprise edition

### ISSUE THREAD

**Issue by lorellav** [DHARPA-Project/kiara#59]
Not possible to install Jupyter notebook in kiara 0.4.36 env

Windows 10 - Enterprise edition
Python 3.9.16
Anaconda 3

**Comment by makkus** [comment]
Not sure what 'not possible to install Jupyter notebook' means. I've tested with a fresh env that had jupyterlab installed and nothing else, and I could run the example notebook that installs kiara without issue (tried 0.4.34 which was the latest version at the time of report). 
I'm closing this, if it still doesn't work, please reopen with details what you try to achieve, what exactly you tried and what the error message(s) are.
