### ISSUE TITLE
Error while getting a value item from the data registry

### ISSUE THREAD

**Issue by theorm** [DHARPA-Project/kiara#9]
When calling `kiara.data_registry.get_value_item` from Lumy, an error is raised by kiara. Kiara is trying to access a `metadata` field that does not exist. 

See attached screenshot. Orange section - Lumy call to Kiara. Green section - Kiara raising an error.
Kiara versions: 

* kiara[all]==0.0.4
* kiara_modules.core==0.0.3
<img width="535" alt="Screen Shot 2021-07-26 at 13 19 09" src="https://user-images.githubusercontent.com/89853/126981237-0c14986a-7dbd-4459-8803-f4e1199e4692.png">

**Comment by makkus** [comment]
I've released a new version of kiara and all the module packages (0.0.9), and a lot of things changed, esp. in relation to data storage.
Could you update and confirm that the issue still exists please?

Btw, the internal organization of the data in the data store has changed, so you'll loose access to this data and will have to re-import. Also ideally run

```
DEVELOP=true kiara data clear-data-store
```
and clear the whole she-bang before you do anything.

**Comment by theorm** [comment]
We solved it today by removing the whole `~/Library/Application Support/kiara` directory. Feel free to close the issue if you think that safe access to "metadata" key is not needed in Kiara.
